name: webview_pro_wkwebview
description: A Flutter plugin that provides a WebView widget based on Apple's WKWebView control.
repository: https://github.com/manuel-escola/flutter-plugins/tree/dev/packages/webview_flutter/webview_flutter_wkwebview
issue_tracker: https://github.com/manuel-escola/flutter-plugins/issues
version: 2.7.1+3

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      ios:
        pluginClass: FLTWebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
  webview_pro_platform_interface:
    git:
      url: https://github.com/manuel-escola/flutter-plugins
      path: packages/webview_flutter/webview_flutter_platform_interface
#    path: ../webview_flutter_platform_interface

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
