name: flutter_webview_pro
description: A Flutter plugin that provides a WebView widget who Support photo upload/take camera and Geolocation.
repository: https://github.com/manuel-escola/flutter-plugins/tree/dev/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/manuel-escola/flutter-plugins/issues
version: 3.0.1+4

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_pro_android:
    git:
      url: https://github.com/manuel-escola/flutter-plugins
      path: packages/webview_flutter/webview_flutter_android
  webview_pro_platform_interface:
    git:
      url: https://github.com/manuel-escola/flutter-plugins
      path: packages/webview_flutter/webview_flutter_platform_interface
  webview_pro_wkwebview:
    git:
      url: https://github.com/manuel-escola/flutter-plugins
      path: packages/webview_flutter/webview_flutter_wkwebview

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
